name: stag
channels:
  - bioconda
  - defaults
  - conda-forge
  - intel
dependencies:
  - python>=3.7
  - nextflow>=21.0
  - hmmer
  - infernal
  - easel
  - numpy
  - pandas
  - scikit-learn<0.24
  - h5py
  - seqtk
  - regex
  - prodigal
