name: stag_0.8.1_tax3
channels:
  - bioconda
  - defaults
  - conda-forge
  - intel
dependencies:
  - python>=3.7
  - hmmer
  - infernal
  - easel
  - numpy
  - pandas
  - scikit-learn<0.24
  - h5py=2.10.0
  - seqtk
  - regex
  - prodigal
